version: '3.7'

services:
  postgres_db:
    image: postgres:10.1-alpine
    env_file: database.conf
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  flask_web:
    build: .
    env_file: database.conf
    command: python3 /flask/main.py
    volumes:
      - .:/flask/
    ports:
      - 8000:8000
    depends_on:
      - postgres_db

volumes:
  postgres_data: